### ISSUE TITLE
Header and additional details

### ISSUE THREAD

**Issue by tracetoio-dias** [tracetoio/styleguide#2]
For the readme have the following suggestions, 

1. Use traceto.io instead of [Traceto](https://github.com/tracetoio/styleguide/blob/master/README.md#tracetoio-projects-code-styleguide) - the capitalised T is only used in official docs.
2. Additional information regarding the resources used and maybe books that will help developers would be a good to have.

**Comment by er-ant** [comment]
@tracetoio-dias 
1. Ok, thanks for notes.
2. Need to think about this, but some links already added.

**Comment by er-ant** [comment]
Hello @tracetoio-dias. Check again please, updated Traceto project name in all Readmes.
Regarding resources - could you provide an example? Because according to my understanding all links were added, for example BEM and codelyzer.
Thanks.
